### ISSUE TITLE
Very small OCR mistake

### ISSUE THREAD

**Issue by Swyter** [bekoha/bekoha.github.io#1]
Hi, I was messing around with the files and noticed what seem like three small localization errors, probably from transcription or OCR, in the Spanish bootup screen.

![imagen](https://user-images.githubusercontent.com/690187/212741737-8f67c953-970c-4234-92f1-40d31be1e061.png)

![imagen](https://user-images.githubusercontent.com/690187/212741048-ff10ba88-6f9e-48dd-882b-22ffac767301.png)

Nothing major, but I thought you might want to know. Hope that helps.

**Comment by bekoha** [comment]
Thank you for bringing this to my attention, was re-typing these by hand and missed these as I don't know the language.
Just fixed this in the texture, will wait a couple of days in case there are other issues that people might report before uploading a new version of the pack.

**Comment by bekoha** [comment]
Noticed another typo at the same screen while looking with fresh eyes ("Quada" instead of "Queda"), all fixed and fresh version uploaded

**Comment by Swyter** [comment]
Great, and pretty darn fast. Mad props to you for a very respectful, tasteful and cohesive texture pack, not a lot of these out there. ¯\\\_(ツ)_/¯
